### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by chookie** [joshpeng/One-Dark#1]
I am using Windows 10 and first install sublime babel then one dark (sublime) then change syntax but it does not change the colours or styles.

```
ext install sublime-babel-vscode
ext install theme-onedark-sublime
```
![onedark_1](https://cloud.githubusercontent.com/assets/4765327/20272198/1f8c2f1c-aa85-11e6-86a6-5bd0262ead97.png)
![onedark_2](https://cloud.githubusercontent.com/assets/4765327/20272207/2368ef08-aa85-11e6-8a82-e40d30e2ce27.png)

**Comment by joshpeng** [comment]
@chookie Have you selected the One Dark theme as your color theme? Please try this:
1. Ctrl+Shift+P
2. Type "color"
3. Select "Preferences: Color Theme"
4. Select "One Dark (Sublime)" or "One Dark+ (Sublime)"

**Comment by chookie** [comment]
Doh!  So sorry, monday-itis.    Thank you for the quick response and great theme.
