### ISSUE TITLE
Using arrow functions in a class causes highlighting to break

### ISSUE THREAD

**Issue by markgoodyear** [joshpeng/One-Dark#2]
See this screenshot: http://d.pr/i/Gsr0/30jybRD2+

I'm not entirely sure if we're supposed to be able to do this, but just wanted to flag up that if we do, it breaks the highlighting for the  rest of the class.

Apart from this issue, this plugin paired with the Sublime Babel plugin has made my One Dark experience _**much**_ better! It always bugged me that there was so much red.

**Comment by joshpeng** [comment]
@markgoodyear Thanks for the catch. Should be fixed in 0.3.3.
Unfortunately I can't get "someMethod" to show up with the same color as "constructor()" or "render()" right now though due to Sublime Babel not tokenizing this scenario with enough differentiation.

**Comment by markgoodyear** [comment]
@joshpeng — Thanks, this works much better 👍
