### ISSUE TITLE
Please re-evaluate your CSS color selections...

### ISSUE THREAD

**Issue by tympapost** [joshpeng/One-Dark#3]
I love this theme, and I know it's more js and python oriented, but CSS coloring could use some attention.
The colors chosen are too similar to each other, and reading CSS can be tiring.
I've included a screenshot:
![ss1](https://cloud.githubusercontent.com/assets/6545650/20388434/72e418b0-accd-11e6-94bc-fd0722dda1ef.png)

**Comment by joshpeng** [comment]
Thanks. I just compared it against Atom's One Dark and you are right. I'll see what can be done.
