### ISSUE TITLE
Support for Flowtype

### ISSUE THREAD

**Issue by kumarharsh** [joshpeng/One-Dark#6]
Hi, I've been using this syntax for quite some time, and it's really great. I am working on React and am using Flow annotations. Would you be interested in adding support for 'type' imports in JS, and some flow-specific syntaxes? Some examples to show where this syntax needs to be improved:

1. Type imports mixed with normal imports:
![image](https://user-images.githubusercontent.com/760112/30733864-67389560-9f96-11e7-9b2f-e792c9f3045d.png)
The first type imported breaks the subsequent highlighting.
2. Putting types on class properties breaks the highlighting:
![image](https://user-images.githubusercontent.com/760112/30733932-b7590c3c-9f96-11e7-846f-f99917b08b51.png)

There are a bunch more issues, but I think you get the idea. Can you add better flow support?

**Comment by joshpeng** [comment]
This is something that would probably need to be implemented on the upstream Sublime Babel extension that this theme utilizes. I have another request over there for this as well, but just haven't had time to dive into it yet. Hopefully will in the nearish future.
