### ISSUE TITLE
Change color of detected links in HTML

### ISSUE THREAD

**Issue by SuperBerny** [joshpeng/One-Dark#8]
aka <a href="google.com"></a> They appear green. Just want to change it to a different color for my own personal sake.
I'm trying to find the <string> that those live in.

**Comment by joshpeng** [comment]
You can bring up the command palette and use `Inspect TM Scopes` to see what rule is currently being applied on the text in question. It may not necessarily be so easy to change since IIRC Code handles links slightly differently than everything else.
